require("loki.core.plugins.lsp-zero")
require("loki.core.plugins.luasnip")
require("loki.core.plugins.nvim-cmp")
-- require("loki.core.plugins.treesitter")
require("loki.core.plugins.lualine")
require("loki.core.plugins.nvim-tree")
require("loki.core.plugins.tmux")
require("loki.core.plugins.autotag")
require("loki.core.plugins.barbar")
require("loki.core.plugins.overseer")
