require("loki.core.plugins.mason")
require("loki.core.plugins.luasnip")
-- require("loki.core.plugins.coq")
require("loki.core.plugins.nvim-cmp")
require("loki.core.plugins.jdtls")
require("loki.core.plugins.lualine")
-- require("loki.core.plugins.nvim-tree")
require("loki.core.plugins.tmux")
require("loki.core.plugins.autotag")
-- require("loki.core.plugins.barbar")
require("loki.core.plugins.overseer")
require("loki.core.plugins.wildcat")
-- require("loki.core.plugins.treesitter")
require("loki.core.plugins.dashboard")
require("loki.core.plugins.oil")
require("loki.core.plugins.workspaces")
require("loki.core.plugins.harpoon")
require("loki.core.plugins.lines")
